gvc:
  name: my-redis-gvc
  locations:
    - name: aws-eu-central-1
      replicas: 2
    - name: aws-us-west-2
      replicas: 2
    - name: aws-us-east-1
      replicas: 2

redis:
  image: redis:7.2
  resources:
    cpu: 200m
    memory: 256Mi
  # serverCommand: redis-server  # Can be overridden based on the version of redis/valkey image
  # extraArgs: "--maxclients 20000 --maxmemory 200mb --maxmemory-policy allkeys-lru"
  # password: fu3h4f9834f8
  volumeset:
    initialCapacity: 20 # GiB
    autoscaling:
      enabled: true
      maxCapacity: 100 # GiB
      minFreePercentage: 10
      scalingFactor: 1.2

sentinel:
  image: redis:7.2
  resources:
    cpu: 200m
    memory: 256Mi
  quorum: 2
  # extraArgs: "--sentinel down-after-milliseconds mymaster 5000 --sentinel failover-timeout mymaster 10000"
  # password: poek290f4238f

firewall:
  internalAllowType: same-gvc # options: same-gvc, same-org, workload-list
  # workloads:
  #   - //gvc/GVC_NAME/workload/WORKLOAD_NAME
