kind: secret
name: {{ include "postgis.secretDatabase.name" . }}
description: PostGIS database config
tags: {{- include "postgis.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username | quote }}
  password: {{ .Values.config.password | quote }}