kind: secret
name: {{ include "maria.secretDatabase.name" . }}
description: MariaDB database configuration
tags:
  {{- include "maria.tags" . | nindent 4 }}
type: dictionary
data:
  MYSQL_DATABASE: {{ .Values.config.db | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.config.rootPassword | quote }}
  MYSQL_USER: {{ .Values.config.user | quote }}
  MYSQL_PASSWORD: {{ .Values.config.password | quote }}