kind: secret
name: {{ include "mongo.secretDatabase.name" . }}
description: MongoDB database configuration
tags:
  {{- include "mongo.tags" . | nindent 4 }}
type: dictionary
data:
  username: {{ .Values.config.username | quote }}
  password: {{ .Values.config.password | quote }}
