---
kind: secret
name: {{ include "clickhouse.secretDatabase.name" . }}
description: Clickhouse database config
tags: {{- include "clickhouse.tags" . | nindent 4 }}
type: dictionary
data:
  password: {{ .Values.database.password | quote }}
  db: {{ .Values.database.name | quote }}
  cluster_name: {{ .Values.clusterName | quote }}